name: Upload to Registry

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/docker.yml

  push:
    needs: build
    runs-on: ubuntu-latest

    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}

    permissions:
      packages: write

    if: github.event_name == 'push'

    steps:
      - uses: actions/download-artifacts@v3
        with:
          path: images

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Push to Registry
        env:
          TAG: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
        run: |
          set -eux

          architectures=("x86_64" "aarch64")
          for arch in "${architectures[@]}"; do
            docker load < images/container-"$arch"/*.tar.gz
            docker tag valfisk:latest-"$arch" ${{ env.TAG }}-"$arch"
            docker push ${{ env.TAG }}-"$arch"
          done

          docker manifest create ${{ env.TAG }} \
            --amend ${{ env.TAG }}-x86_64 \
            --amend ${{ env.TAG }}-aarch64

          docker manifest push ${{ env.TAG }}
